In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_salaries = pd.read_csv('salaries.csv')

In [3]:
df_salaries

       company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [5]:
df_salaries.describe()

       salary_more_then_100k
count                 16.000
mean                   0.625
std                    0.500
min                    0.000
25%                    0.000
50%                    1.000
75%                    1.000
max                    1.000

In [6]:
df_salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   company                16 non-null     object
 1   job                    16 non-null     object
 2   degree                 16 non-null     object
 3   salary_more_then_100k  16 non-null     int64
dtypes: int64(1), object(3)
memory usage: 644.0+ bytes

In [9]:
df_salaries.groupby('company').count()

            job  degree  salary_more_then_100k
company
abc pharma    4       4                      4
facebook      6       6                      6
google        6       6                      6

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
df_salaries_le = df_salaries
df_salaries_le.company = le.fit_transform(df_salaries_le.company)

In [12]:
df_salaries_le

    company                  job     degree  salary_more_then_100k
0         2      sales executive  bachelors                      0
1         2      sales executive    masters                      0
2         2     business manager  bachelors                      1
3         2     business manager    masters                      1
4         2  computer programmer  bachelors                      0
5         2  computer programmer    masters                      1
6         0      sales executive    masters                      0
7         0  computer programmer  bachelors                      0
8         0     business manager  bachelors                      0
9         0     business manager    masters                      1
10        1      sales executive  bachelors                      1
11        1      sales executive    masters                      1
12        1     business manager  bachelors                      1
13        1     business manager    masters                      1
14        1  computer programmer  bachelors                      1
15        1  computer programmer    masters                      1

In [13]:
df_salaries_le = df_salaries
df_salaries_le.job = le.fit_transform(df_salaries_le.job)

In [14]:
df_salaries_le

    company  job     degree  salary_more_then_100k
0         2    2  bachelors                      0
1         2    2    masters                      0
2         2    0  bachelors                      1
3         2    0    masters                      1
4         2    1  bachelors                      0
5         2    1    masters                      1
6         0    2    masters                      0
7         0    1  bachelors                      0
8         0    0  bachelors                      0
9         0    0    masters                      1
10        1    2  bachelors                      1
11        1    2    masters                      1
12        1    0  bachelors                      1
13        1    0    masters                      1
14        1    1  bachelors                      1
15        1    1    masters                      1

In [15]:
df_salaries_le = df_salaries
df_salaries_le.degree = le.fit_transform(df_salaries_le.degree)

In [16]:
df_salaries_le

    company  job  degree  salary_more_then_100k
0         2    2       0                      0
1         2    2       1                      0
2         2    0       0                      1
3         2    0       1                      1
4         2    1       0                      0
5         2    1       1                      1
6         0    2       1                      0
7         0    1       0                      0
8         0    0       0                      0
9         0    0       1                      1
10        1    2       0                      1
11        1    2       1                      1
12        1    0       0                      1
13        1    0       1                      1
14        1    1       0                      1
15        1    1       1                      1

In [31]:
X = df_salaries_le[['company', 'job' , 'degree']]

In [32]:
X

    company  job  degree
0         2    2       0
1         2    2       1
2         2    0       0
3         2    0       1
4         2    1       0
5         2    1       1
6         0    2       1
7         0    1       0
8         0    0       0
9         0    0       1
10        1    2       0
11        1    2       1
12        1    0       0
13        1    0       1
14        1    1       0
15        1    1       1

In [18]:
y = df_salaries_le.salary_more_then_100k

In [ ]:
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.compose import ColumnTransformer

# ct = ColumnTransformer(
#     transformers=[
#         ('encoder', OneHotEncoder(), [0])
#     ],
#     remainder='passthrough'
# )

# X = ct.fit_transform(df_salaries_le)

In [33]:
X

    company  job  degree
0         2    2       0
1         2    2       1
2         2    0       0
3         2    0       1
4         2    1       0
5         2    1       1
6         0    2       1
7         0    1       0
8         0    0       0
9         0    0       1
10        1    2       0
11        1    2       1
12        1    0       0
13        1    0       1
14        1    1       0
15        1    1       1

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train , y_test = train_test_split(X,y,test_size=0.2)